# Generated by Django 3.2.13 on 2022-06-11 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rpms_main', '0002_auto_20220611_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_visits', models.PositiveIntegerField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_visit', to=settings.AUTH_USER_MODEL)),
                ('time_of_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_of_visits', to='rpms_main.appointments')),
            ],
        ),
    ]
