# Generated by Django 3.2.13 on 2022-06-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpms_main', '0003_previousvisits'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
    ]
